<?php

$lang = array(
  '__app_fileupload' => 'File Upload',
  'module__fileupload_fileupload' => 'File Upload',
  'filestorage__fileupload_fileUploadStorage' => 'File Upload',
  'frontnavigation_fileupload' => 'File Upload',
  'fileupload_firstTitle' => 'File Upload',
  'fileupload_secondTitle' => 'Upload your file',
  'fileupload_uploadField' => 'Choose your file',
  'fileupload_filesuploaded' => '{# [1:file][?:files]} already uploaded',
  'fileupload_by' => 'By :',
  'fileupload_file' => 'File',
  'fileupload_goto' => 'Go to file',
  'fileupload_downloadfile' => 'Download file',
  'fileupload_link' => 'Link',
  'fileupload_moderate' => 'Moderate',
  'fileupload_moderate_delete' => 'Delete',
  'fileupload_upload_ok' => 'Files correctly uploaded',
  'fileupload_file_deleted' => 'File deleted',
  'fileupload_file_delete_error'  => 'An error has occurred during deleting the file',
  'menutab__fileupload' => 'File Upload',
  'menutab__fileupload_icon' => 'upload',
  'menu__fileupload_fileupload' => 'File Upload',
  'menu__fileupload_fileupload_setting' => 'Settings',
  'menu__fileupload_setting' => 'Settings',
  'fileupload_general_setting' => 'General settings',
  'fileupload_moderator_setting' => 'Moderators',
  'fileupload_allowed_group' => 'Groups allowed to upload',
  'fileupload_moderator_group' => 'Groups that can moderate content',
  'acplogs__fileupload_setting_permission_change' => 'Fileupload - Permissions changed',
);
